### ISSUE TITLE
Update dev container for Android develoment

### ISSUE THREAD

**Issue by SebKister** [SebKister/MNemoLink#75]

**Comment by speleobrad** [comment]
Started working on this and managed to get past the libserialport (created my own fork of it, fixed the TERMIOX issue and then used that in MNemoLink)... but am getting stuck with signing (?):

https://github.com/speleobrad/MNemoLink/actions/runs/7684652189/job/20941404346#step:5:173

I'm not into Android development, so can't tell what's the issue. Happy to PR what I got so far, so you can continue from there.

**Comment by SebKister** [comment]
You get that issue because the release APK build is configured to use my android developer signing key, private not tracked by repo, which explains the error. You can change the  buildType section of android/app/build.gradle to 
 buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

I  should have removed the TODO and comment in the file commited on the repo or left it with the  signingConfigs.debug config.

**Comment by speleobrad** [comment]
Been reading about it and left builtType.release intact, but added builtType.debug with signingConfig = null, which seem to work. 

I PRed it all - you can see it in action here: 
https://github.com/speleobrad/MNemoLink/actions/runs/7686190236
